### ISSUE TITLE
AEM Front Extension not adding script tag

### ISSUE THREAD

**Issue by aguacatedan** [kevinweber/aem-front-extension#2]
Hi,

We've been trying this extension for chrome but it seems like it's not doing anything. It's simply not adding the script tag at the end of the doc no matter what we try, thus not reloading the page. If we add the script tag to the document manually it reloads when there are changes. The npm package works perfectly fine, though.

Is there any log file we can inspect in order to research what's the cause or some kind of troubleshooting we can do ourselves? 

Our setup is:
Windows 7 64bit
AEM 6.2
Google Chrome Version 58.0.3029.96 (64-bit)

**Comment by aguacatedan** [comment]
Nevermind, we figure this one out. Most of or pages use a vanity URL and we found out that it only works when you see the page from the direct url to the page (http://HOST/content/../../..).

Awesome plugin btw

**Comment by kevinweber** [comment]
Hi Daniel,
thanks for reaching out to me. What URL are you using for AEM? Is it `localhost:4502/...path/` or are you using a different port? The Chrome extension currently only works for localhost and port 4502. However, I can add an option so you can define your own domain and port. Is that what you need?

Best regards,
Kevin

**Comment by aguacatedan** [comment]
We have AEM running in localhost:4502, the problem is that if the page isn't open from the absolute URI, let's say: `localhost:4502/content/company/home.html` and instead it's opened from a different URL `localhost:4502/home.html` because the page uses a vanity URL, then the extension doesn't work. Doesn't add the script tag. 

One of my coworkers dug into the code and found that in the background.js, if you add an empty string to the allowedPaths, it would work for us. Is there any way to make this an option? 

I hope I'm making myself clear about the problem.

**Comment by kevinweber** [comment]
Hi Daniel,
thanks for your feedback.
I just added two new input fields that allow you to specify a custom list of domains and paths. If you insert `*` into the field for paths, it should act like your described "empty string".
Let me know if everything works.

The extension is now at version 2.1 in the Chrome app store.
